name=V2Device
version=1
author=Versio Duo
maintainer=Kay Sievers <kay@vrfy.org>
sentence=Device Metadata Interface
paragraph=Device Metadata Interface
category=Device Control
url=https://github.com/versioduo/V2Device
architectures=samd
depends=ArduinoJson, V2Memory, V2Cryptography
